version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: messenger_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: messenger
      POSTGRES_PASSWORD: messenger_dev_pass
      POSTGRES_DB: messenger_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: